language: python
python:
- '3.6'
services:
- docker
install:
- pip install pipenv
- pipenv install --dev
script: make coverage-upload
deploy:
  provider: script
  script: >
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && make docker-build docker-push
  on:
    branch: master
env:
  global:
  - secure: cG6b8vqHbdKwIhsS+qQgf4W+42S4S2lGN+9F2w+/xutZ0EizxCqP1sWWAOzzJoEy+8lzEjuNDlcL2mxEOEGhRgKDo7srgjW+Zk8Yxqj8dU7pYvIWtVYXUTaSXhA+0FeWX4DV+et7fBbDxNKajR27hz2mjZLVBogf26W2d1ohGJJ5incxAxx70eh2w7sGSyFuDtWIVlhf+VEL0Hpy6PZlC+wJgX6v917hsz04J2cshtO9d0x0pQs3cbfGj92Ttl6QXXAvmhcU40aCaqX41Kjt8HrYdBZhn1X9H7zZJJ962MrU7otKL1gVrN/JxIcdeEzuF5OaoQn5l0LLXExm+elSJ+I7i7DQznIGRbzZGQ34xiJcn0YRf+pjMUSm/OehprRXklDYRWjOx0CvrXPP/IJ3yUAbLKvqZxMtIKdzfgLTv8Ll0KUkfFs7ulC9YLHS6LtesarLMsnryGQbqoRJZJDOWl83XR/1ParrtKi0681aptNBwszilkdfauz3oYOx7zoHrnR+erTc0F0tefy26SHhNy7uQmLJxaOBsR8sACNG9CHU4u79LLtObwbZ260wAdY/xxL2PB2YHb0VbEQgYt26iLLaY3pTUuHzrAjfslSMzaFFTWidIDd/JdFwTZgj5Nq3krr+g2OjJAswOyKqjFepYIbGWyfF5HEGh0CxAh9iL3Y=
  - secure: W1FNGJ1ObGFEVR98fJaARLfTdO/lxcbbm85T1mK5SVUmZHpyb4MYcNOLs5iQUSkmlR7qMPhXaZFYWNrE0byBZSLbUsYwFpUw6ofPCbmOv9/fhaIfAlwVPCLcQN99YAmnfe4NqpY6p2ZyVuWLY+ZUXyhc1+xDrxhTaxfGbm8gZ923yFIG8jfxzTbSlf/3ZEgixM+Fl/pgrevoh3BKz/QboCQOvndn5IO79TWXp0j2TCY/5mRmjOn9GcFt+Si54YucTQ7mEN2kRLDYfTscycITDHwoWhZ8KGASxjZBqNErITwQvrQYCXfq0s5NTVn/sN/sCox15PVln361XPwT2welPAO2aQqnBPolpq7bAQ2cSLPzwptDGIogtrWtiQAHqFvnzDzioeYchqDfLxyShAwO48nLHPiXZ/VgZbciL6jEwc5bphTB3dmtirbIypjS6xZOXwJ+I0WBA4ecfwjfWOvrDZ1BPcOqLunQ08GmkAKIGCfMnMKliTN/b9QXvvNAEg/TJI5g2Gn/rUPUJc8mncVQMNwqI0c521Hb8nJWXa1ppxURGTzG2KqKSCAfTnLFi97QFq+vzxpvg99aax/XxRMKjVo3QkIl/D/+iXpTmMQ9tJyMTczb1RFbq8ytqIneLLt9cEBc+vuVJbNiK3e/rgzqrUfOB4m/tL3Az3mMPfdUqrc=
